#UserParameter=ble.temp[*],cut -d',' -f1 /home/it/6_blmulti/sensor_cache/sensor_$1 | tr -d '\r '
#UserParameter=ble.hum[*], cut -d',' -f2 /home/it/6_blmulti/sensor_cache/sensor_$1 | tr -d '\r '
#UserParameter=ble.batt[*],cut -d',' -f3 /home/it/6_blmulti/sensor_cache/sensor_$1 | tr -d '\r '

UserParameter=ble.temp[*],cut -d',' -f3 /home/it/iotmon/logs/sensor_$1.csv | tr -d '\r '
UserParameter=ble.hum[*],cut -d',' -f4 /home/it/iotmon/logs/sensor_$1.csv | tr -d '\r '
UserParameter=ble.batt[*],cut -d',' -f5 /home/it/iotmon/logs/sensor_$1.csv | tr -d '\r '
UserParameter=ble.delay[*],cut -d',' -f6 /home/it/iotmon/logs/sensor_$1.csv | tr -d '\r '
UserParameter=ble.status[*],cut -d',' -f3 /home/it/iotmon/logs/sensor_$1.status | tr -d '\r '
